// resources/js/components/AvatarSelector.tsx
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Trash2, Upload } from "lucide-react";
import { useRef, useState } from "react";

interface AvatarSelectorProps {
    modelValue?: File | null;
    currentAvatarUrl?: string | null;
    label?: string;
    description?: string;
    acceptedTypes?: string[];
    disabled?: boolean;
    error?: string;
    onChange?: (file: File | null) => void;
    onDelete?: () => void;
}

export function AvatarSelector({
    modelValue,
    currentAvatarUrl,
    label = "Avatar",
    description = "JPG, PNG or WebP. 2MB Max.",
    acceptedTypes = ["image/jpeg", "image/jpg", "image/png", "image/webp"],
    disabled = false,
    error,
    onChange,
    onDelete,
}: AvatarSelectorProps) {
    const fileInputRef = useRef<HTMLInputElement>(null);
    const [previewUrl, setPreviewUrl] = useState<string | null>(null);

    const formatBytes = (bytes: number): string => {
        if (bytes === 0) return "0 Bytes";
        const k = 1024;
        const sizes = ["Bytes", "KB", "MB"];
        const i = Math.floor(Math.log(bytes) / Math.log(k));
        return (
            Math.round((bytes / Math.pow(k, i)) * 100) / 100 + " " + sizes[i]
        );
    };

    const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        const file = event.target.files?.[0] || null;
        if (file) {
            const url = URL.createObjectURL(file);
            setPreviewUrl(url);
        }
        onChange?.(file);
    };

    const handleRemove = () => {
        if (fileInputRef.current) {
            fileInputRef.current.value = "";
        }
        setPreviewUrl(null);
        onChange?.(null);
    };

    const handleDeleteAvatar = () => {
        handleRemove();
        onDelete?.();
    };

    const openFileDialog = () => {
        fileInputRef.current?.click();
    };

    const displayUrl = previewUrl || currentAvatarUrl;

    return (
        <div className="space-y-4">
            <div className="flex min-w-56 flex-wrap items-center justify-between gap-4">
                <Avatar className="h-20 w-20">
                    <AvatarImage src={displayUrl || undefined} alt={label} />
                    <AvatarFallback className="text-lg">
                        {label.charAt(0).toUpperCase()}
                    </AvatarFallback>
                </Avatar>

                <div className="flex flex-col gap-2">
                    <Button
                        type="button"
                        variant="outline"
                        disabled={disabled}
                        onClick={openFileDialog}
                        className="w-full"
                    >
                        <Upload className="mr-2 h-4 w-4" />
                        Upload image
                    </Button>

                    {currentAvatarUrl && (
                        <Button
                            type="button"
                            variant="ghost"
                            size="sm"
                            disabled={disabled}
                            onClick={handleDeleteAvatar}
                            className="text-gray-500 hover:text-gray-700"
                        >
                            <Trash2 className="h-4 w-4" />
                        </Button>
                    )}
                </div>
            </div>

            <input
                ref={fileInputRef}
                type="file"
                accept={acceptedTypes.join(",")}
                onChange={handleFileChange}
                className="hidden"
                disabled={disabled}
            />

            {modelValue && (
                <p className="text-xs text-gray-600 dark:text-gray-400">
                    {modelValue.name} {formatBytes(modelValue.size)}
                    <Button
                        type="button"
                        variant="link"
                        size="sm"
                        className="ml-2 p-0 text-red-600"
                        disabled={disabled}
                        onClick={handleRemove}
                    >
                        Remove
                    </Button>
                </p>
            )}

            {error && (
                <p className="text-sm text-red-600 dark:text-red-400">
                    {error}
                </p>
            )}
        </div>
    );
}

// resources/js/components/avatar/AvatarSelector.vue
<script setup lang="ts">
import type { AvatarUploadProps } from "@/types/avatar.ts";
import { computed } from "vue";

const props = withDefaults(
    defineProps<AvatarUploadProps & { error?: string }>(),
    {
        label: "Avatar",
        description: "JPG, PNG or WebP. 2MB Max.",
        acceptedTypes: () => [
            "image/jpeg",
            "image/jpg",
            "image/png",
            "image/webp",
        ],
        disabled: false,
        required: false,
    },
);

const emit = defineEmits<{
    "update:modelValue": [value: File | null | undefined];
    change: [value: File | null | undefined];
    remove: [];
    deleteAvatar: [];
}>();

const buttonLabel = computed(() => {
    return "Upload image";
});

const previewUrl = computed(() => {
    if (props.modelValue) return URL.createObjectURL(props.modelValue);
    return props.currentAvatarUrl ?? undefined;
});

const formatBytes = (bytes: number): string => {
    if (bytes === 0) return "0 Bytes";
    const k = 1024;
    const sizes = ["Bytes", "KB", "MB"];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return Math.round((bytes / Math.pow(k, i)) * 100) / 100 + " " + sizes[i];
};

const handleFileChange = (file: File | null | undefined) => {
    emit("update:modelValue", file);
    emit("change", file);
};

const handleDeleteAvatar = () => {
    emit("update:modelValue", null);
    emit("deleteAvatar");
};

const handleRemove = (removeFileFn: () => void) => {
    removeFileFn();
    emit("update:modelValue", null);
    emit("remove");
};
</script>

<template>
    <div>
        <UFileUpload
            v-slot="{ open, removeFile }"
            :modelValue="modelValue"
            :accept="acceptedTypes.join(',')"
            :disabled="disabled"
            @update:modelValue="handleFileChange"
        >
            <div
                class="flex min-w-56 flex-wrap items-center justify-between gap-4"
            >
                <UAvatar
                    size="3xl"
                    :src="previewUrl"
                    :alt="label"
                    :initials="label"
                />
                <UButton
                    :label="buttonLabel"
                    color="neutral"
                    variant="outline"
                    :disabled="disabled"
                    @click="open()"
                />

                <template v-if="currentAvatarUrl">
                    <UButton
                        color="neutral"
                        variant="ghost"
                        icon="i-lucide-trash"
                        :disabled="disabled"
                        @click="handleDeleteAvatar()"
                        class="text-gray-500 dark:text-gray-300"
                    />
                </template>
            </div>

            <p
                v-if="modelValue"
                class="mt-1.5 text-xs text-gray-600 dark:text-gray-400"
            >
                {{ modelValue.name }} {{ formatBytes(modelValue.size) }}
                <UButton
                    label="Remove"
                    color="error"
                    variant="link"
                    size="xs"
                    class="p-0"
                    :disabled="disabled"
                    @click="handleRemove(removeFile)"
                />
            </p>
        </UFileUpload>

        <!-- Display validation errors from Laravel -->
        <p v-if="error" class="text-sm text-red-600 dark:text-red-400">
            {{ error }}
        </p>
    </div>
</template>

<style scoped></style>
