// resources/js/pages/profile/General.vue
<script setup lang="ts">
import AvatarSelector from "@/components/avatar/AvatarSelector.vue";
import ProfileLayout from "@/pages/profile/Layout.vue";
import type { User } from "@/types/shared.ts";
import { destroy } from "@/wayfinder/actions/App/Http/Controllers/Profile/UserAvatarController.ts";
import { update } from "@/wayfinder/actions/App/Http/Controllers/Profile/UserProfileController.ts";
import { router, useForm } from "@inertiajs/vue3";

interface GeneralProfilePageProps {
    user: User;
}

const props = defineProps<GeneralProfilePageProps>();

const form = useForm<{
    name: string;
    email: string;
    avatar: File | null | undefined;
    _method: string;
}>({
    name: props.user.name,
    email: props.user.email,
    avatar: null as File | null | undefined,
    _method: "PUT",
});

const submit = () => {
    form.post(update().url, {
        preserveScroll: true,
        onSuccess: () => {
            form.reset("avatar");
            useToast().add({
                title: "Success",
                description: "Profile updated successfully",
                color: "success",
            });
        },
        onError: (errors) => {
            console.error("Validation errors:", errors);
        },
    });
};

const removeAvatar = () => {
    router.delete(destroy(), {
        preserveScroll: true,
        onSuccess: () => {
            useToast().add({
                title: "Success",
                description: "Avatar removed successfully",
                color: "success",
            });
        },
    });
};
</script>

<template>
    <ProfileLayout>
        <form id="settings" @submit.prevent="submit">
            <UPageCard
                title="General"
                description="General account settings related to your profile."
                variant="naked"
                orientation="horizontal"
                class="mb-4"
            >
                <UButton
                    form="settings"
                    label="Save changes"
                    color="neutral"
                    type="submit"
                    class="w-fit lg:ms-auto"
                    :loading="form.processing"
                    :disabled="form.processing"
                />
            </UPageCard>

            <UPageCard variant="subtle">
                <UFormField
                    name="name"
                    label="Name"
                    description="Your full name."
                    v-model="form.name"
                    required
                    :error="form.errors.name"
                    class="flex items-start justify-between gap-4 max-sm:flex-col"
                >
                    <UInput
                        v-model="form.name"
                        name="name"
                        autocomplete="off"
                        class="w-full lg:w-80"
                    />
                </UFormField>

                <USeparator />

                <UFormField
                    name="email"
                    label="Email"
                    description="The email address you use for authentication and notifications."
                    v-model="form.email"
                    required
                    :error="form.errors.email"
                    class="flex items-start justify-between gap-4 max-sm:flex-col"
                >
                    <UInput
                        v-model="form.email"
                        name="email"
                        type="email"
                        autocomplete="off"
                        class="w-full lg:w-80"
                    />
                </UFormField>

                <USeparator />

                <UFormField
                    name="avatar"
                    label="Profile photo"
                    description="Used for attribution on time offs requests and other events."
                    v-model="form.avatar"
                    class="flex items-start justify-between gap-4 max-sm:flex-col"
                >
                    <AvatarSelector
                        v-model="form.avatar"
                        :current-avatar-url="props.user.avatar.src"
                        :label="form.name"
                        :error="form.errors.avatar"
                        @deleteAvatar="removeAvatar"
                    />
                </UFormField>
            </UPageCard>
        </form>
    </ProfileLayout>
</template>

<style scoped></style>

// resources/js/pages/profile/General.tsx
import { AvatarSelector } from "@/components/AvatarSelector";
import { Button } from "@/components/ui/button";
import {
    Card,
    CardContent,
    CardDescription,
    CardHeader,
    CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Separator } from "@/components/ui/separator";
import { ProfileLayout } from "@/layouts/ProfileLayout";
import { destroy } from "@/wayfinder/actions/App/Http/Controllers/Profile/UserAvatarController";
import { update } from "@/wayfinder/actions/App/Http/Controllers/Profile/UserProfileController";
import { router, useForm } from "@inertiajs/react";
import { useState } from "react";

interface GeneralProfilePageProps {
    user: {
        name: string;
        email: string;
        avatar: {
            src: string;
        };
    };
}

export default function General({ user }: GeneralProfilePageProps) {
    const [avatar, setAvatar] = useState<File | null>(null);

    const { data, setData, post, processing, errors } = useForm({
        name: user.name,
        email: user.email,
        avatar: null as File | null,
        _method: "PUT",
    });

    const submit = (e: React.FormEvent) => {
        e.preventDefault();
        const formData = new FormData();
        formData.append("name", data.name);
        formData.append("email", data.email);
        formData.append("_method", "PUT");
        if (avatar) {
            formData.append("avatar", avatar);
        }

        post(update().url, {
            data: formData,
            preserveScroll: true,
            onSuccess: () => {
                setAvatar(null);
                console.log("Profile updated successfully");
            },
            onError: (errors) => {
                console.error("Validation errors:", errors);
            },
        });
    };

    const removeAvatar = () => {
        router.delete(destroy(), {
            preserveScroll: true,
            onSuccess: () => {
                console.log("Avatar removed successfully");
            },
        });
    };

    return (
        <ProfileLayout>
            <form id="settings" onSubmit={submit}>
                <Card className="mb-4">
                    <CardHeader>
                        <CardTitle>General</CardTitle>
                        <CardDescription>
                            General account settings related to your profile.
                        </CardDescription>
                    </CardHeader>
                    <CardContent>
                        <Button
                            form="settings"
                            type="submit"
                            className="w-fit lg:ms-auto"
                            disabled={processing}
                        >
                            {processing ? "Saving..." : "Save changes"}
                        </Button>
                    </CardContent>
                </Card>

                <Card>
                    <CardContent className="space-y-6 pt-6">
                        <div className="flex items-start justify-between gap-4 max-sm:flex-col">
                            <div className="space-y-1">
                                <Label htmlFor="name">Name</Label>
                                <p className="text-sm text-gray-600">
                                    Your full name.
                                </p>
                            </div>
                            <Input
                                id="name"
                                name="name"
                                value={data.name}
                                onChange={(e) =>
                                    setData("name", e.target.value)
                                }
                                className="w-full lg:w-80"
                            />
                        </div>
                        {errors.name && (
                            <p className="text-sm text-red-600">
                                {errors.name}
                            </p>
                        )}

                        <Separator />

                        <div className="flex items-start justify-between gap-4 max-sm:flex-col">
                            <div className="space-y-1">
                                <Label htmlFor="email">Email</Label>
                                <p className="text-sm text-gray-600">
                                    The email address you use for authentication
                                    and notifications.
                                </p>
                            </div>
                            <Input
                                id="email"
                                name="email"
                                type="email"
                                value={data.email}
                                onChange={(e) =>
                                    setData("email", e.target.value)
                                }
                                className="w-full lg:w-80"
                            />
                        </div>
                        {errors.email && (
                            <p className="text-sm text-red-600">
                                {errors.email}
                            </p>
                        )}

                        <Separator />

                        <div className="flex items-start justify-between gap-4 max-sm:flex-col">
                            <div className="space-y-1">
                                <Label>Profile photo</Label>
                                <p className="text-sm text-gray-600">
                                    Used for attribution on time offs requests
                                    and other events.
                                </p>
                            </div>
                            <AvatarSelector
                                modelValue={avatar}
                                currentAvatarUrl={user.avatar.src}
                                label={data.name}
                                error={errors.avatar}
                                onChange={setAvatar}
                                onDelete={removeAvatar}
                            />
                        </div>
                    </CardContent>
                </Card>
            </form>
        </ProfileLayout>
    );
}
